### ISSUE TITLE
Integrate Google Analytics

### ISSUE THREAD

**Issue by briankalwat** [briankalwat/telics#11]

**Comment by briankalwat** [comment]
@djacris if you have a chance at some point today, can you go to http://www.google.com/analytics/standard/ and sign up/create an account for analytics? Otherwise, I can do it but I will need your password.

**Comment by djacris** [comment]
My djacris1@gmail.com is already signed up for my old site.  Would you suggest creating a new account for Telics.com to feed into or just using mine.

**Comment by briankalwat** [comment]
@djacris I think it'd be best to create a new one using hr@telics.com or something that will always exist with the company (not a personal email address). We can always add access to other email addresses, but the owner should be a permanent account.

**Comment by djacris** [comment]
telicsanalytics@gmail.com

**Comment by briankalwat** [comment]
Putting this here for my reference:

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-66499627-1', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by djacris** [comment]
Are you good with this then?  I don't need to do anything else to that account?

**Comment by briankalwat** [comment]
no, I just need to add that code, and then once we move it to telics.com it should start tracking.
