### ISSUE TITLE
Blue Line on Services and Careers page

### ISSUE THREAD

**Issue by djacris** [briankalwat/telics#12]
There is a blue line that goes across the top of the top row of cards on the careers and services pages.

**Comment by briankalwat** [comment]
@djacris when logging stuff like this, including screenshots is really helpful for when I go to try and reproduce the issue! Thank you sir!

**Comment by djacris** [comment]
![image](https://cloud.githubusercontent.com/assets/13837128/9312300/e508f08e-44e9-11e5-9a0b-ba5805a63692.png)


Does this printscreen and paste show up?

**Comment by briankalwat** [comment]
@djacris I was able to see it in the screenshot but I deleted it because it had login info/credit card numbers in it. ;) Was that Chrome in Windows 8.1?

**Comment by djacris** [comment]
Yeah.

Josh Wyatt
Area Manager - IT
TELICS
864.884.2890
telics.com

**Comment by briankalwat** [comment]
@djacris I'm unable to reproduce this – are you still seeing the problem?

**Comment by djacris** [comment]
![image](https://cloud.githubusercontent.com/assets/13837128/9525901/6a53ec18-4cb4-11e5-837d-514962271eee.png)

**Comment by djacris** [comment]
It isn't there on IE11.  Is in Chrome.

**Comment by briankalwat** [comment]
@djacris I just looked at it in Chrome (44.0.2403.157) on Windows 8.1 and I'm not seeing it. However, mine is on a VM. We may have to just troubleshoot this when we get together to do CMS training.

**Comment by djacris** [comment]
Alright.  I can also check on another machine to see if it is just mine.
